### ISSUE TITLE
Plugin incompatible with new di.fm design

### ISSUE THREAD

**Issue by timdp** [Bitcrusher/Digitally-Imported-XBMC-plugin#15]
I'm getting a "Script error" when I try to launch the plugin, and see this error in Kodi's log:

```
17:27:44 T:1608078400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.audio.di.fm/default.py", line 440, in <module>
    MusicAddonInstance.run()
  File "/storage/.kodi/addons/plugin.audio.di.fm/default.py", line 209, in run
    channelMeta = json.loads(re_channelData.findall(html)[0])
IndexError: list index out of range
-->End of Python script error report<--
```

This is a clean install of the plugin on OpenELEC 5 on my RPi 2. It used to work fine on my old one, but I can't remember when I last used it. It looks like di.fm has a new design, so that's probably the cause?

**Comment by GertBurger** [comment]
See PR #12

**Comment by matosimi** [comment]
try my fix:

https://github.com/matosimi/Digitally-Imported-XBMC-plugin/tree/fix-channel-regexp

i just finished it.

**Comment by timdp** [comment]
Sorry I missed the PR. I only looked at the open issues, not the PRs.

@matosimi Your fix works, thanks!

**Comment by Bitcrusher** [comment]
Hi guys :)
I've had a lot of stuff going on lately, new house/job/baby, so it's been kinda hard to find the time ;)
I finally found it and I've just pushed v3.0.6 to the Kodi repo and it's of course already available here in this repo.

Enjoy the tunes (again)
